services:

  steedos:
    image: steedos/templates:3.0.0
    build: 
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - './steedos-storage:/steedos-storage'
      - './.steedos:/app/.steedos'
    environment:
      - STEEDOS_LICENSE=
      - ROOT_URL=http://127.0.0.1
      - TRANSPORTER=redis://redis:6379
      - CACHER=redis://redis:6379/1
      - STEEDOS_BULLMQ_REDIS=redis://redis:6379/2
      - MONGO_URL=mongodb://mongodb:27017/templates
      - STEEDOS_ENABLE_WORKFLOW=true

  redis:
    image: redis:6.2.10
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
 
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "steedos", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongodb:/data/db'

  mongodb-init:
    image: mongodb/mongodb-community-server:7.0-ubi8
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"

volumes:
  steedos-mongodb:
    driver: local
